// src/assets/icons/university/index.ts
const icons: { [key: string]: any } = {
  snu: require('./snu.png'),
  yon: require('./yon.png'),
  kor: require('./kor.jpg'),
  sogang: require('./sogang.gif'),
  hanyang: require('./hanyang.jpg'),
  skku: require('./skku.png'),
  cau: require('./cau.png'),
  ewha: require('./ewha.png'),
  uos: require('./uos.png'),
  kyunghee: require('./kyunghee.png'),
  konkuk: require('./konkuk.jpg'),
  snue: require('./snue.jpg'),
  hufs: require('./hufs.gif'),
  kcue: require('./kcue.png'),
  dongguk: require('./dongguk.png'),
  hongik: require('./hongik.jpg'),
  sookmyung: require('./sookmyung.png'),
  seoultech: require('./seoultech.png'),
  ajou: require('./ajou.jpg'),
  soongsil: require('./soongsil.jpg'),
  ginue: require('./ginue.jpg'),
  kookmin: require('./kookmin.png'),
  inha: require('./inha.png'),
  sejong: require('./sejong.png'),
  pusan: require('./pusan.png'),
  sungshin: require('./sungshin.jpg'),
  dankook: require('./dankook.png'),
  knu: require('./knu.png'),
  kau: require('./kau.gif'),
  incheon: require('./incheon.png'),
  kwangwoon: require('./kwangwoon.png'),
  chonnam: require('./chonnam.png'),
  chungnam: require('./chungnam.jpg'),
  smu: require('./smu.jpg'),
  gachon: require('./gachon.jpg'),
  duksung: require('./duksung.gif'),
  myongji: require('./myongji.jpg'),
  catholic: require('./catholic.jpg'),
  dongduk: require('./dongduk.png'),
  // kyonggi: require('./kyonggi.png'),
  swuk: require('./swuk.jpg')
};

export default icons;
